# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

RUN npm install --production --ignore-scripts

# Bundle app source
COPY . .

# Build the project
RUN npm run build

# Expose any ports if needed, else CMD
CMD ["node", "build/index.js"]
